### ISSUE TITLE
[Ongoing] Reduce bundle sizes.

### ISSUE THREAD

**Issue by benjamn** [apollographql/react-apollo#2743]
> Note: This issue tracks work that began in PR #2661.

In the same spirit as https://github.com/apollographql/apollo-client/issues/4324, the bundle footprint of the `react-apollo` package (currently [32.7KB minified, 8.7KB after gzip](https://bundlephobia.com/result?p=react-apollo@2.4.0)) could be, well, smaller.

This issue will serve as a place for discussing and coordinating bundle size improvements of any kind, including but not limited to the following techniques:
* Reimplementing surprisingly heavy dependencies locally, a la 4bac03af40690db68fa79e4fc7df944a7256d861.
* Making it easier to import specific parts of the `react-apollo` package, by supporting multiple entry points, e.g. `react-apollo/browser` and `react-apollo/server`. Note: this may be less important if we can rely on effective tree-shaking and ESM bundling.
* Transforming imports to be more specific using a compiler plugin, so that `import { SpecificThing } from "react-apollo"` becomes `import { SpecificThing } from "react-apollo/lib/specific-thing"`. If we end up pursuing this approach for `apollo-client`, we will no doubt reuse the same tools here. Note: because this would impose new build-time requirements, we should wait to try this approach until it seems like the only/best option.
* Somehow code-splitting the library, even though dynamic `import()` is not an option for libraries that must be consumed by bundlers with different runtime implementations of dynamic modules.
* Introducing a production bundle in addition to the development bundle, with more aggressive elimination of unnecessary code (e.g. error strings).
* Playing to the strengths of the advanced bundlers that our most bundle-size-conscious users are likely to be using.

Pull requests are more than welcome! Here's a list of PRs that have contributed (or promise to contribute) to reducing bundle sizes:
- [x] Changes released in `react-apollo@2.5.0`: #2661
- [x] Holistic application-level bundle measurement: #2839
- [ ] Reductions inspired by `examples/rollup`: #2842

**Comment by sventschui** [comment]
@benjamn one thing about the bundle size are the graphql queries. I understand that apollo uses some parts of the queries (e.g. default values). Is there a way to throw away part of the queries on the client side and replace the queries with a hash (similar to automated persisted queries)?

I guess this would help a lot in practice, what do you think?

**Comment by hwillson** [comment]
Reducing bundle sizes is an on-going battle, and is something we keep in the fore front of our minds with every PR merged. All of the work associated with this issue has been merged, and we'll continue to work on bundle size reduction with every release. Thanks all!
